services:
  nginx:
    image: nginx:1.27.3-alpine
    restart: unless-stopped
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /dev/shm:/dev/shm
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/etc/nginx/html
      - ./xray/xray_generated_configs:/var/www/subs:ro
    labels:
      - sh.acme.autoload.domain=self-host

  acme.sh:
    image: neilpang/acme.sh:latest
    container_name: acme.sh
    command: daemon
    stdin_open: true
    tty: true
    restart: no
    volumes:
      - ./acmeout:/acme.sh
      - ./nginx/ssl:/etc/nginx/ssl
      - /var/run/docker.sock:/var/run/docker.sock
  
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /dev/shm:/dev/shm
      - ./xray/xray_config.json:/etc/xray/config.json
      - ./nginx/ssl:/etc/xray/ssl

networks:
  default:
    external: true
    name: self-host
